# Deploy to Azure Kubernetes Service
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:

  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'b8d72312-ee7a-49b9-8b99-77f27fefb42d'
  imageRepository: 'shashbanexamplevote'
  containerRegistry: 'atulmakshelm.azurecr.io'
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)'
  
  # Kubernetes Namespace
  k8sNamespace: 'default'
  imagePullSecret: 'atulmakshelm538a-auth'
  kubeconn: 'kodeAKS-default'

stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build job
    
    steps:
    - checkout: none
    - script: echo HEllow wporls

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  jobs:
  - deployment: deployDev
    environment: 'shashbanexamplevote'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: KubernetesManifest@0
            displayName: Create imagePullSecret
            inputs:
              action: 'createSecret'
              kubernetesServiceConnection: $(kubeconn)
              namespace: 'default'
              secretType: 'dockerRegistry'
              secretName: 'secret'
              dockerRegistryEndpoint: 'atulmakshelm'
