# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  # ========================================================================
  #                          Mandatory variables 
  # ========================================================================

  # Update Azure.ServiceConnectionId value with AzureRm service endpoint.
  Azure.ServiceConnection: 'RMPM'
  # Update ACR.Name value with ACR name. Please note ACR names should be all lower-case and alphanumeric only.
  ACR.Name: 'shashbanpipelinesdotnetcoree0c9'

  # ========================================================================
  #                           Optional variables 
  # ========================================================================

  ACR.ImageName: '$(ACR.Name):$(Build.BuildId)'
  ACR.FullName: '$(ACR.Name).azurecr.io'
  ACR.ImageTag: '$(ACR.FullName)/$(ACR.ImageName)'
  
steps:
- script: docker build -f Dockerfile -t $(ACR.ImageName) .
  displayName: 'docker build'
- script: docker tag $(ACR.ImageName) $(ACR.ImageTag) .
  displayName: 'docker build'
- task: Docker@1
  displayName: 'push image'
  inputs:
    azureSubscriptionEndpoint: $(Azure.ServiceConnection)
    azureContainerRegistry: $(ACR.FullName)
    imageName: $(ACR.ImageName)
    command: push
